name: README build

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository to master branch.
        uses: actions/checkout@v3
      - name: Setup Nodejs.
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: Cache dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Install dependencies
        run: npm install -g pnpm && pnpm i
      - name: Generate README file
        run: pnpm gen
      - name: Commit and Push new README.md to the repository
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
